server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-main
spring.datasource.username=ewm
spring.datasource.password=ewm
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always
stat.server.url=http://localhost:9090