server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-stats
spring.datasource.username=ewm
spring.datasource.password=ewm
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.sql.init.mode=always