server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/ewm-stats
spring.datasource.username=ewm
spring.datasource.password=ewm
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#????????? ??? ???????
stat.server.url:http://localhost:9090